// src/pages/Disclaimer.jsx
import React from "react";
import {Container, Heading, Link, ListItem, Text, UnorderedList, VStack,} from "@chakra-ui/react";

function Disclaimer() {
    return (
        <Container maxW="container.lg" py={8}>
            <VStack align="stretch" spacing={4}>
                <Heading as="h1" size="xl">
                    Disclaimer
                </Heading>
                <Text>Updated at 2025-02-18</Text>

                <Text>
                    Butterflies of Zimbabwe hereby grants you access to (“the Website”)
                    and invites you to purchase the services offered here.
                </Text>

                <Heading as="h2" size="lg">
                    Definitions and key terms
                </Heading>
                <Text>
                    To help explain things as clearly as possible in this Disclaimer,
                    every time any of these terms are referenced, are strictly defined as:
                </Text>
                <UnorderedList spacing={2}>
                    <ListItem>
                        <strong>Cookie:</strong> small amount of data generated by a website
                        and saved by your web browser. It is used to identify your browser,
                        provide analytics, remember information about you such as your
                        language preference or login information.
                    </ListItem>
                    <ListItem>
                        <strong>Company:</strong> when this policy mentions “Company,” “we,”
                        “us,” or “our,” it refers to Bilda Bees Pvt Ltd, P.O.Box 1019 that
                        is responsible for your information under this Disclaimer.
                    </ListItem>
                    <ListItem>
                        <strong>Service:</strong> refers to the service provided by
                        Butterflies of Zimbabwe as described in the relative terms (if
                        available) and on this platform.
                    </ListItem>
                    <ListItem>
                        <strong>Website:</strong> site, which can be accessed via this URL:
                    </ListItem>
                    <ListItem>
                        <strong>You:</strong> a person or entity that is registered with
                        Butterflies of Zimbabwe to use the Services.
                    </ListItem>
                </UnorderedList>
                <Text>
                    This Disclaimer was created with{" "}
                    <Link
                        href="https://termify.io"
                        target="_blank"
                        rel="noopener noreferrer"
                        color="teal.500"
                    >
                        Termify
                    </Link>
                    .
                </Text>

                <Heading as="h2" size="lg">
                    Limited liability
                </Heading>
                <Text>
                    Butterflies of Zimbabwe endeavours to update and/or supplement the
                    content of the app on a regular basis. Despite our care and attention,
                    content may be incomplete and/or incorrect.
                </Text>
                <Text>
                    The materials offered on the app are offered without any form of
                    guarantee or claim to their correctness. These materials can be
                    changed at any time without prior notice from Butterflies of
                    Zimbabwe.
                </Text>
                <Text>
                    Particularly, all prices on the app are stated subject to typing and
                    programming errors. No liability is assumed for the implications of
                    such errors. No agreement is concluded on the basis of such errors.
                </Text>
                <Text>
                    Butterflies of Zimbabwe shall not bear any liability for hyperlinks to
                    websites or services of third parties included on the app. From our
                    app, you can visit other websites by following hyperlinks to such
                    external sites. While we strive to provide only quality links to
                    useful and ethical websites, we have no control over the content and
                    nature of these sites. These links to other websites do not imply a
                    recommendation for all the content found on these sites. Site owners
                    and content may change without notice and may occur before we have the
                    opportunity to remove a link which may have gone ‘bad’.
                </Text>
                <Text>
                    Please be also aware that when you leave our app, other sites may have
                    different privacy policies and terms which are beyond our control.
                    Please be sure to check the Privacy Policies of these sites as well as
                    their "Terms of Service" before engaging in any business or uploading
                    any information.
                </Text>

                <Heading as="h2" size="lg">
                    Links to Other Websites Disclaimer
                </Heading>
                <Text>
                    This Disclaimer applies only to the Services. The Services may contain
                    links to other websites not operated or controlled by Butterflies of
                    Zimbabwe. We are not responsible for the content, accuracy or opinions
                    expressed in such websites, and such websites are not investigated,
                    monitored or checked for accuracy or completeness by us. Please
                    remember that when you use a link to go from the Services to another
                    website, our Privacy Policy is no longer in effect. Your browsing and
                    interaction on any other website, including those that have a link on
                    our platform, is subject to that website’s own rules and policies.
                    Such third parties may use their own cookies or other methods to
                    collect information about you. If You click on a third party link, You
                    will be directed to that third party's site. We strongly advise You to
                    review the Privacy Policy and Terms of every site You visit.
                </Text>
                <Text>
                    We have no control over and assume no responsibility for the content,
                    privacy policies or practices of any third party sites or services.
                </Text>

                <Heading as="h2" size="lg">
                    Errors and Omissions Disclaimer
                </Heading>
                <Text>Butterflies of Zimbabwe is not responsible for any content, code or any other imprecision.</Text>
                <Text>Butterflies of Zimbabwe does not provide warranties or guarantees.</Text>
                <Text>
                    In no event shall Butterflies of Zimbabwe be liable for any special,
                    direct, indirect, consequential, or incidental damages or any damages
                    whatsoever, whether in an action of contract, negligence or other
                    tort, arising out of or in connection with the use of the Service or
                    the contents of the Service. Butterflies of Zimbabwe reserves the
                    right to make additions, deletions, or modifications to the contents
                    on the Service at any time without prior notice.
                </Text>

                <Heading as="h2" size="lg">
                    General Disclaimer
                </Heading>
                <Text>
                    The Butterflies of Zimbabwe Service and its contents are provided "as
                    is" and "as available" without any warranty or representations of any
                    kind, whether express or implied. Butterflies of Zimbabwe is a
                    distributor and not a publisher of the content supplied by third
                    parties; as such, Butterflies of Zimbabwe exercises no editorial
                    control over such content and makes no warranty or representation as
                    to the accuracy, reliability or currency of any information, content,
                    service or merchandise provided through or accessible via the
                    Butterflies of Zimbabwe Service. Without limiting the foregoing,
                    Butterflies of Zimbabwe specifically disclaims all warranties and
                    representations in any content transmitted on or in connection with
                    the Butterflies of Zimbabwe Service or on sites that may appear as
                    links on the Butterflies of Zimbabwe Service, or in the products
                    provided as a part of, or otherwise in connection with, the
                    Butterflies of Zimbabwe Service, including without limitation any
                    warranties of merchantability, fitness for a particular purpose or
                    non-infringement of third party rights. No oral advice or written
                    information given by Butterflies of Zimbabwe or any of its affiliates,
                    employees, officers, directors, agents, or the like will create a
                    warranty. Price and availability information is subject to change
                    without notice. Without limiting the foregoing, Butterflies of
                    Zimbabwe does not warrant that the Butterflies of Zimbabwe Service
                    will be uninterrupted, uncorrupted, timely, or error-free.
                </Text>

                <Heading as="h2" size="lg">
                    Copyright Disclaimer
                </Heading>
                <Text>
                    All intellectual property rights concerning these materials are vested
                    in Butterflies of Zimbabwe. Copying, distribution and any other use of
                    these materials is not permitted without the written permission of
                    Butterflies of Zimbabwe, except and only to the extent otherwise
                    provided in regulations of mandatory law (such as the right to quote),
                    unless otherwise stated for certain materials.
                </Text>

                <Heading as="h2" size="lg">
                    Educational Disclosure
                </Heading>
                <Text>
                    Any Information provided by Butterflies of Zimbabwe is for educational
                    purposes only, and is not to be interpreted as a recommendation for a
                    specific treatment plan, product, or course of action. Butterflies of
                    Zimbabwe is a distributor and not a publisher of the content supplied
                    by third parties; as such, Butterflies of Zimbabwe exercises no
                    editorial control over such content and makes no warranty or
                    representation as to the accuracy, reliability or currency of any
                    information or educational content provided through or accessible via
                    Butterflies of Zimbabwe. Without limiting the foregoing, Butterflies
                    of Zimbabwe specifically disclaims all warranties and representations
                    in any content transmitted on or in connection with Butterflies of
                    Zimbabwe or on sites that may appear as links on Butterflies of
                    Zimbabwe, or in the products provided as a part of, or otherwise in
                    connection with, the Butterflies of Zimbabwe. No oral advice or
                    written information given by Butterflies of Zimbabwe or any of its
                    affiliates, employees, officers, directors, agents, or the like will
                    create a warranty.
                </Text>

                <Heading as="h2" size="lg">
                    Advertising Disclosure
                </Heading>
                <Text>
                    This app may contain third party advertisements and links to third
                    party sites. Butterflies of Zimbabwe does not make any representation
                    as to the accuracy or suitability of any of the information contained
                    in those advertisements or sites and does not accept any
                    responsibility or liability for the conduct or content of those
                    advertisements and sites and the offerings made by the third parties.
                </Text>
                <Text>
                    Advertising keeps Butterflies of Zimbabwe and many of the websites and
                    services you use free of charge. We work hard to make sure that ads
                    are safe, unobtrusive, and as relevant as possible.
                </Text>
                <Text>
                    Third party advertisements and links to other sites where goods or
                    services are advertised are not endorsements or recommendations by
                    Butterflies of Zimbabwe of the third party sites, goods or services.
                    Butterflies of Zimbabwe takes no responsibility for the content of any
                    of the ads, promises made, or the quality/reliability of the products
                    or services offered in all advertisements.
                </Text>

                <Heading as="h2" size="lg">
                    Testimonials Disclosure
                </Heading>
                <Text>
                    Any testimonials provided on this platform are opinions of those
                    providing them. The information provided in the testimonials is not to
                    be relied upon to predict results in your specific situation. The
                    results you experience will be dependent on many factors including but
                    not limited to your level of personal responsibility, commitment, and
                    abilities, in addition to those factors that you and/or Butterflies of
                    Zimbabwe may not be able to anticipate.
                </Text>
                <Text>
                    We will give honest testimonials to our visitors regardless of any
                    discount. Any product or service that we test are individual
                    experiences, reflecting real life experiences. The testimonials could
                    be displayed on audio, text or video and are not necessarily
                    representative of all of those who will use our products and/or
                    services.
                </Text>
                <Text>
                    Butterflies of Zimbabwe does not guarantee the same results as the
                    testimonials given on our platform. Testimonials presented on
                    Butterflies of Zimbabwe are applicable to the individuals writing
                    them, and may not be indicative of future success of any other
                    individuals.
                </Text>
                <Text>
                    Please don’t hesitate to contact us if you would like to know more
                    about testimonials, discounts, or any of the products/services that we
                    review.
                </Text>

                <Heading as="h2" size="lg">
                    Your Consent
                </Heading>
                <Text>
                    We've updated our Disclaimer to provide you with complete
                    transparency into what is being set when you visit our site and how
                    it's being used. By using our app, registering an account, or making a
                    purchase, you hereby consent to our Disclaimer and agree to its terms.
                </Text>

                <Heading as="h2" size="lg">
                    Changes To Our Disclaimer
                </Heading>
                <Text>
                    Should we update, amend or make any changes to this document so that
                    they accurately reflect our Service and policies. Unless otherwise
                    required by law, those changes will be prominently posted here. Then,
                    if you continue to use the Service, you will be bound by the updated
                    Disclaimer. If you do not want to agree to this or any updated
                    Disclaimer, you can delete your account.
                </Text>

                <Heading as="h2" size="lg">
                    Contact Us
                </Heading>
                <Text>Don't hesitate to contact us if you have any questions regarding this Disclaimer.</Text>
                <UnorderedList spacing={2}>
                    <ListItem>Via Email: admin@bbdevs.xyz</ListItem>
                </UnorderedList>
            </VStack>
        </Container>
    );
}

export default Disclaimer;
