// src/pages/Eula.jsx
import React from "react";
import {Container, Heading, Link, ListItem, Text, UnorderedList, VStack,} from "@chakra-ui/react";

function Eula() {
    return (
        <Container maxW="container.lg" py={8}>
            <VStack align="stretch" spacing={4}>

                <Heading as="h1" size="xl">
                    End-User License Agreement
                </Heading>
                <Text>Updated at 2025-02-17</Text>

                <Text>
                    Butterflies of Zimbabwe hereby grants you access to (“the Website”)
                    and invites you to purchase the services offered here.
                </Text>

                <Heading as="h2" size="lg">
                    Definitions and key terms
                </Heading>
                <Text>
                    To help explain things as clearly as possible in this Eula, every time
                    any of these terms are referenced, are strictly defined as:
                </Text>
                <UnorderedList spacing={2}>
                    <ListItem>
                        <strong>Cookie:</strong> small amount of data generated by a website
                        and saved by your web browser...
                    </ListItem>
                    <ListItem>
                        <strong>Company:</strong> when this policy mentions “Company,”
                        “we,” “us,” or “our,” it refers to Bilda Bees Pvt Ltd, P.O.Box 1019
                        that is responsible for your information under this Eula.
                    </ListItem>
                    <ListItem>
                        <strong>Country:</strong> Zimbabwe
                    </ListItem>
                    <ListItem>
                        <strong>Service:</strong> refers to the service provided by
                        Butterflies of Zimbabwe...
                    </ListItem>
                    <ListItem>
                        <strong>Third-party service:</strong> refers to advertisers...
                    </ListItem>
                    <ListItem>
                        <strong>You:</strong> a person or entity that is registered with
                        Butterflies of Zimbabwe to use the Services.
                    </ListItem>
                </UnorderedList>
                <Text>
                    This EULA was created with{" "}
                    <Link
                        href="https://termify.io"
                        target="_blank"
                        rel="noopener noreferrer"
                        color="teal.500"
                    >
                        Termify
                    </Link>
                    .
                </Text>

                <Heading as="h2" size="lg">
                    Introduction
                </Heading>
                <Text>
                    This End User License Agreement (the “Agreement”) is a binding
                    agreement between you (“End User”, “you” or “your”) and Bilda Bees Pvt
                    Ltd (“Company”, “we”, “us” or “our”). This Agreement governs the
                    relationship between you and us, and your use of the Company
                    Butterflies of Zimbabwe...
                </Text>
                <Text>
                    If you are using the app on behalf of your employer or other entity...
                </Text>

                <Heading as="h2" size="lg">
                    License
                </Heading>
                <Text>
                    Subject to the terms of this Agreement and, if applicable, those terms
                    provided in the License Agreement, Butterflies of Zimbabwe grants you
                    a limited, non-exclusive...
                </Text>

                <Heading as="h2" size="lg">
                    Restrictions
                </Heading>
                <Text>You agree not to, and you will not permit others to:</Text>
                <UnorderedList spacing={2}>
                    <ListItem>
                        License, sell, rent, lease, assign, distribute, transmit, host,
                        outsource...
                    </ListItem>
                    <ListItem>
                        Modify, make derivative works of, disassemble, decrypt, reverse
                        compile...
                    </ListItem>
                    <ListItem>
                        Remove, alter or obscure any proprietary notice of Butterflies of
                        Zimbabwe...
                    </ListItem>
                </UnorderedList>

                <Heading as="h2" size="lg">
                    Intellectual Property
                </Heading>
                <Text>
                    All intellectual property rights, including copyrights, patents,
                    patent disclosures and inventions...
                </Text>

                <Heading as="h2" size="lg">
                    Your Suggestions
                </Heading>
                <Text>
                    Any feedback, comments, ideas, improvements or suggestions
                    (collectively, "Suggestions") provided by you to Butterflies of
                    Zimbabwe...
                </Text>

                <Heading as="h2" size="lg">
                    Modifications to Application
                </Heading>
                <Text>
                    Butterflies of Zimbabwe reserves the right to modify, suspend or
                    discontinue, temporarily or permanently, the Application...
                </Text>

                <Heading as="h2" size="lg">
                    Updates to Application
                </Heading>
                <Text>
                    Butterflies of Zimbabwe may from time to time provide enhancements or
                    improvements to the features/ functionality of the Application...
                </Text>

                <Heading as="h2" size="lg">
                    Term and Termination
                </Heading>
                <Text>
                    This Agreement shall remain in effect until terminated by you or
                    Butterflies of Zimbabwe...
                </Text>

                <Heading as="h2" size="lg">
                    Indemnification
                </Heading>
                <Text>
                    You agree to indemnify, defend and hold harmless Butterflies of
                    Zimbabwe and its officers, directors...
                </Text>

                <Heading as="h2" size="lg">
                    No Warranties
                </Heading>
                <Text>
                    The Application is provided to you "AS IS" and "AS AVAILABLE" and with
                    all faults and defects...
                </Text>

                <Heading as="h2" size="lg">
                    Limitation of Liability
                </Heading>
                <Text>
                    Notwithstanding any damages that you might incur, the entire liability
                    of Butterflies of Zimbabwe...
                </Text>

                <Heading as="h2" size="lg">
                    Severability
                </Heading>
                <Text>
                    If any provision of this Agreement is held to be unenforceable or
                    invalid...
                </Text>

                <Heading as="h2" size="lg">
                    Waiver
                </Heading>
                <Text>
                    No failure to exercise, and no delay in exercising, on the part of
                    either party, any right...
                </Text>

                <Heading as="h2" size="lg">
                    Amendments to this Agreement
                </Heading>
                <Text>
                    Butterflies of Zimbabwe reserves the right, at its sole discretion, to
                    modify or replace this Agreement at any time...
                </Text>

                <Heading as="h2" size="lg">
                    Governing Law
                </Heading>
                <Text>
                    The laws of Zimbabwe, excluding its conflicts of law rules, shall
                    govern this Agreement...
                </Text>

                <Heading as="h2" size="lg">
                    Changes to this agreement
                </Heading>
                <Text>
                    We reserve the exclusive right to make changes to this Agreement from
                    time to time...
                </Text>

                <Heading as="h2" size="lg">
                    No Employment or Agency Relationship
                </Heading>
                <Text>
                    No provision of this Agreement, or any part of relationship between
                    you and Butterflies of Zimbabwe...
                </Text>

                <Heading as="h2" size="lg">
                    Equitable Relief
                </Heading>
                <Text>
                    You acknowledge and agree that your breach of this Agreement would
                    cause Butterflies of Zimbabwe irreparable harm...
                </Text>

                <Heading as="h2" size="lg">
                    Headings
                </Heading>
                <Text>
                    The headings in this Agreement are for reference only and shall not
                    limit the scope...
                </Text>

                <Heading as="h2" size="lg">
                    Geographic Restrictions
                </Heading>
                <Text>
                    The Company is based in Zimbabwe and provided for access and use
                    primarily by persons located in Zimbabwe...
                </Text>

                <Heading as="h2" size="lg">
                    Limitation of Time to File Claims
                </Heading>
                <Text>
                    Any cause of action or claim you may have arising out of or relating
                    to this agreement or the app must be commenced within one (1) year...
                </Text>

                <Heading as="h2" size="lg">
                    Entire Agreement
                </Heading>
                <Text>
                    The Agreement constitutes the entire agreement between you and
                    Butterflies of Zimbabwe regarding your use of the Application...
                </Text>

                <Heading as="h2" size="lg">
                    Contact Us
                </Heading>
                <Text>Don't hesitate to contact us if you have any questions about this Agreement.</Text>
                <UnorderedList spacing={2}>
                    <ListItem>Via Email: [email protected]</ListItem>
                </UnorderedList>
            </VStack>
        </Container>
    );
}

export default Eula;
