// src/pages/Privacy.jsx
import React from "react";
import {Container, Heading, Link, ListItem, Text, UnorderedList, VStack,} from "@chakra-ui/react";

function Privacy() {
    return (
        <Container maxW="container.lg" py={8}>
            <VStack align="stretch" spacing={4}>

                <Heading as="h1" size="xl">
                    Privacy Policy
                </Heading>
                <Text>Updated at 2025-02-17</Text>

                <Text>
                    Butterflies of Zimbabwe (“we,” “our,” or “us”) is committed to
                    protecting your privacy. This Privacy Policy explains how your
                    personal information is collected, used, and disclosed by Butterflies
                    of Zimbabwe.
                </Text>
                <Text>
                    This Privacy Policy applies to our website, and its associated
                    subdomains (collectively, our “Service”) alongside our application,
                    Butterflies of Zimbabwe. By accessing or using our Service, you
                    signify that you have read, understood, and agree to our collection,
                    storage, use, and disclosure of your personal information as described
                    in this Privacy Policy and our Terms of Service. This Privacy Policy
                    was created with{" "}
                    <Link
                        href="https://termify.io"
                        target="_blank"
                        rel="noopener noreferrer"
                        color="teal.500"
                    >
                        Termify
                    </Link>
                    .
                </Text>

                <Heading as="h2" size="lg">
                    Definitions and key terms
                </Heading>
                <Text>
                    To help explain things as clearly as possible in this Privacy Policy,
                    every time any of these terms are referenced, are strictly defined as:
                </Text>
                <UnorderedList spacing={2}>
                    <ListItem>
                        <strong>Cookie:</strong> small amount of data generated by a website
                        and saved by your web browser...
                    </ListItem>
                    <ListItem>
                        <strong>Company:</strong> when this policy mentions “Company,”
                        “we,” “us,” or “our,” it refers to Bilda Bees Pvt Ltd, P.O.Box 1019
                        that is responsible for your information under this Privacy Policy.
                    </ListItem>
                    <ListItem>
                        <strong>Country:</strong> where Butterflies of Zimbabwe or the
                        owners/founders of Butterflies of Zimbabwe are based, in this case
                        is Zimbabwe
                    </ListItem>
                    <ListItem>
                        <strong>Customer:</strong> refers to the company, organization or
                        person that signs up to use the Butterflies of Zimbabwe Service...
                    </ListItem>
                    <ListItem>
                        <strong>Device:</strong> any internet connected device such as a
                        phone, tablet, computer or any other device that can be used to
                        visit Butterflies of Zimbabwe...
                    </ListItem>
                    <ListItem>
                        <strong>IP address:</strong> Every device connected to the Internet
                        is assigned a number known as an Internet protocol (IP) address...
                    </ListItem>
                    <ListItem>
                        <strong>Personnel:</strong> refers to those individuals who are
                        employed by Butterflies of Zimbabwe...
                    </ListItem>
                    <ListItem>
                        <strong>Personal Data:</strong> any information that directly,
                        indirectly, or in connection with other information...
                    </ListItem>
                    <ListItem>
                        <strong>Service:</strong> refers to the service provided by
                        Butterflies of Zimbabwe...
                    </ListItem>
                    <ListItem>
                        <strong>Third-party service:</strong> refers to advertisers, contest
                        sponsors...
                    </ListItem>
                    <ListItem>
                        <strong>Website:</strong> Butterflies of Zimbabwe's site...
                    </ListItem>
                    <ListItem>
                        <strong>You:</strong> a person or entity that is registered with
                        Butterflies of Zimbabwe to use the Services.
                    </ListItem>
                </UnorderedList>

                <Heading as="h2" size="lg">
                    Information automatically collected
                </Heading>
                <Text>
                    There is some information like your Internet Protocol (IP) address
                    and/or browser and device characteristics — is collected automatically
                    when you visit our platform...
                </Text>
                <Text>
                    We automatically collect certain information when you visit, use or
                    navigate the platform. This information does not reveal your specific
                    identity...
                </Text>

                <Heading as="h2" size="lg">
                    Personnel
                </Heading>
                <Text>
                    If you are a Butterflies of Zimbabwe worker or applicant, we collect
                    information you voluntarily provide to us...
                </Text>

                <Heading as="h2" size="lg">
                    Sale of Business
                </Heading>
                <Text>
                    We reserve the right to transfer information to a third party in the
                    event of a sale, merger or other transfer of all or substantially all
                    of the assets...
                </Text>

                <Heading as="h2" size="lg">
                    Affiliates
                </Heading>
                <Text>
                    We may disclose information (including personal information) about you
                    to our Corporate Affiliates...
                </Text>

                <Heading as="h2" size="lg">
                    Governing Law
                </Heading>
                <Text>
                    This Privacy Policy is governed by the laws of Zimbabwe without regard
                    to its conflict of laws provision...
                </Text>

                <Heading as="h2" size="lg">
                    Your Consent
                </Heading>
                <Text>
                    We've updated our Privacy Policy to provide you with complete
                    transparency into what is being set when you visit our site...
                </Text>

                <Heading as="h2" size="lg">
                    Links to Other Websites
                </Heading>
                <Text>
                    This Privacy Policy applies only to the Services. The Services may
                    contain links to other websites not operated or controlled by
                    Butterflies of Zimbabwe...
                </Text>

                <Heading as="h2" size="lg">
                    Advertising
                </Heading>
                <Text>
                    This app may contain third party advertisements and links to third
                    party sites. Butterflies of Zimbabwe does not make any representation
                    as to the accuracy...
                </Text>

                <Heading as="h2" size="lg">
                    Cookies for Advertising
                </Heading>
                <Text>
                    These cookies collect information over time about your online activity
                    on the app and other online services...
                </Text>

                <Heading as="h2" size="lg">
                    Cookies
                </Heading>
                <Text>
                    Butterflies of Zimbabwe uses "Cookies" to identify the areas of our
                    website that you have visited...
                </Text>

                <Heading as="h2" size="lg">
                    Blocking and disabling cookies and similar technologies
                </Heading>
                <Text>
                    Wherever you're located you may also set your browser to block cookies
                    and similar technologies...
                </Text>

                <Heading as="h2" size="lg">
                    Remarketing Services
                </Heading>
                <Text>
                    We use remarketing services. What Is Remarketing? In digital marketing,
                    remarketing (or retargeting)...
                </Text>

                <Heading as="h2" size="lg">
                    Payment Details
                </Heading>
                <Text>
                    In respect to any credit card or other payment processing details you
                    have provided us, we commit that this confidential information...
                </Text>

                <Heading as="h2" size="lg">
                    Kids' Privacy
                </Heading>
                <Text>
                    We collect information from kids under the age of 13 just to better
                    our services. If You are a parent or guardian...
                </Text>

                <Heading as="h2" size="lg">
                    Changes To Our Privacy Policy
                </Heading>
                <Text>
                    We may change our Service and policies, and we may need to make
                    changes to this Privacy Policy...
                </Text>

                <Heading as="h2" size="lg">
                    Third-Party Services
                </Heading>
                <Text>
                    We may display, include or make available third-party content
                    (including data, information, applications...) or provide links to
                    third-party websites or services...
                </Text>

                <Heading as="h2" size="lg">
                    Tracking Technologies
                </Heading>
                <UnorderedList spacing={2}>
                    <ListItem>
                        <strong>Google Maps API</strong>
                        <Text>
                            Google Maps API may collect information from You and from Your
                            Device for security purposes...
                        </Text>
                    </ListItem>
                    <ListItem>
                        <strong>Local Storage</strong>
                        <Text>
                            Local Storage sometimes known as DOM storage, provides web apps
                            with methods and protocols for storing client-side data...
                        </Text>
                    </ListItem>
                </UnorderedList>

                <Heading as="h2" size="lg">
                    Information about General Data Protection Regulation (GDPR)
                </Heading>
                <Text>
                    We may be collecting and using information from you if you are from
                    the European Economic Area (EEA)...
                </Text>

                <Heading as="h2" size="lg">
                    What is GDPR?
                </Heading>
                <Text>
                    GDPR is an EU-wide privacy and data protection law that regulates how
                    EU residents' data is protected...
                </Text>

                <Heading as="h2" size="lg">
                    What is personal data?
                </Heading>
                <Text>
                    Any data that relates to an identifiable or identified individual.
                    GDPR covers a broad spectrum of information...
                </Text>
                <UnorderedList spacing={2}>
                    <ListItem>
                        Personal data collected must be processed in a fair, legal, and
                        transparent way...
                    </ListItem>
                    <ListItem>
                        Personal data should only be collected to fulfil a specific purpose...
                    </ListItem>
                    <ListItem>
                        Personal data should be held no longer than necessary...
                    </ListItem>
                    <ListItem>
                        People covered by the GDPR have the right to access their own
                        personal data...
                    </ListItem>
                </UnorderedList>

                <Heading as="h2" size="lg">
                    Why is GDPR important?
                </Heading>
                <Text>
                    GDPR adds some new requirements regarding how companies should protect
                    individuals' personal data...
                </Text>

                <Heading as="h2" size="lg">
                    Individual Data Subject's Rights - Data Access, Portability and Deletion
                </Heading>
                <Text>
                    We are committed to helping our customers meet the data subject rights
                    requirements of GDPR...
                </Text>

                <Heading as="h2" size="lg">
                    California Residents
                </Heading>
                <Text>
                    The California Consumer Privacy Act (CCPA) requires us to disclose
                    categories of Personal Information...
                </Text>
                <UnorderedList spacing={2}>
                    <ListItem>Right to Know and Access...</ListItem>
                    <ListItem>Right to Equal Service...</ListItem>
                    <ListItem>Right to Delete...</ListItem>
                    <ListItem>
                        Request that a business that sells a consumer's personal data, not
                        sell the consumer's personal data.
                    </ListItem>
                </UnorderedList>

                <Heading as="h2" size="lg">
                    California Online Privacy Protection Act (CalOPPA)
                </Heading>
                <Text>
                    CalOPPA requires us to disclose categories of Personal Information we
                    collect and how we use it...
                </Text>
                <UnorderedList spacing={2}>
                    <ListItem>Right to Know and Access...</ListItem>
                    <ListItem>Right to Equal Service...</ListItem>
                    <ListItem>Right to Delete...</ListItem>
                    <ListItem>Right to request that a business not sell...</ListItem>
                </UnorderedList>

                <Heading as="h2" size="lg">
                    Contact Us
                </Heading>
                <Text>Don't hesitate to contact us if you have any questions.</Text>
                <UnorderedList spacing={2}>
                    <ListItem>Via Email: admin@bbdevs.xyz</ListItem>
                </UnorderedList>
            </VStack>
        </Container>
    );
}

export default Privacy;
