// src/pages/Terms.jsx
import React from "react";
import {Container, Heading, Link, ListItem, Text, UnorderedList, VStack,} from "@chakra-ui/react";

function Terms() {
    return (
        <Container maxW="container.lg" py={8}>
            <VStack align="stretch" spacing={4}>

                <Heading as="h1" size="xl">
                    Terms &amp; Conditions
                </Heading>
                <Text>Updated at 2025-02-17</Text>

                <Heading as="h2" size="lg">
                    General Terms
                </Heading>
                <Text>
                    By accessing and placing an order with Butterflies of Zimbabwe, you
                    confirm that you are in agreement with and bound by the terms of
                    service contained in the Terms &amp; Conditions outlined below. These
                    terms apply to the entire website and any email or other type of
                    communication between you and Butterflies of Zimbabwe.
                </Text>
                <Text>
                    Under no circumstances shall Butterflies of Zimbabwe team be liable
                    for any direct, indirect, special, incidental or consequential
                    damages, including, but not limited to, loss of data or profit,
                    arising out of the use, or the inability to use, the materials on this
                    site, even if Butterflies of Zimbabwe team or an authorized
                    representative has been advised of the possibility of such damages. If
                    your use of materials from this site results in the need for
                    servicing, repair or correction of equipment or data, you assume any
                    costs thereof.
                </Text>
                <Text>
                    Butterflies of Zimbabwe will not be responsible for any outcome that
                    may occur during the course of usage of our resources. We reserve the
                    rights to change prices and revise the resources usage policy in any
                    moment. This Terms &amp; Conditions was created with{" "}
                    <Link
                        href="https://termify.io"
                        target="_blank"
                        rel="noopener noreferrer"
                        color="teal.500"
                    >
                        Termify
                    </Link>
                    .
                </Text>

                <Heading as="h2" size="lg">
                    License
                </Heading>
                <Text>
                    Butterflies of Zimbabwe grants you a revocable, non-exclusive,
                    non-transferable, limited license to download, install and use the app
                    strictly in accordance with the terms of this Agreement.
                </Text>
                <Text>
                    These Terms &amp; Conditions are a contract between you and
                    Butterflies of Zimbabwe (referred to in these Terms &amp; Conditions
                    as &quot;Butterflies of Zimbabwe&quot;, &quot;us&quot;,
                    &quot;we&quot; or &quot;our&quot;), the provider of the Butterflies of
                    Zimbabwe website and the services accessible from the Butterflies of
                    Zimbabwe website (which are collectively referred to in these Terms
                    &amp; Conditions as the &quot;Butterflies of Zimbabwe Service&quot;).
                </Text>
                <Text>
                    You are agreeing to be bound by these Terms &amp; Conditions. If you
                    do not agree to these Terms &amp; Conditions, please do not use the
                    Butterflies of Zimbabwe Service. In these Terms &amp; Conditions,
                    &quot;you&quot; refers both to you as an individual and to the entity
                    you represent. If you violate any of these Terms &amp; Conditions, we
                    reserve the right to cancel your account or block access to your
                    account without notice.
                </Text>

                <Heading as="h2" size="lg">
                    Definitions and key terms
                </Heading>
                <Text>To help explain things as clearly as possible in this Terms &amp; Conditions, every time any of
                    these terms are referenced, are strictly defined as:</Text>
                <UnorderedList spacing={2}>
                    <ListItem>
                        <strong>Cookie:</strong> small amount of data generated by a
                        website...
                    </ListItem>
                    <ListItem>
                        <strong>Company:</strong> when this policy mentions “Company,”
                        “we,” “us,” or “our,” it refers to Bilda Bees Pvt Ltd, P.O.Box 1019
                        that is responsible for your information under this Terms &amp;
                        Conditions.
                    </ListItem>
                    <ListItem>
                        <strong>Country:</strong> where Butterflies of Zimbabwe or the
                        owners/founders of Butterflies of Zimbabwe are based, in this case
                        is
                    </ListItem>
                    <ListItem>
                        <strong>Device:</strong> any internet connected device such as a
                        phone, tablet, computer or any other device that can be used to
                        visit Butterflies of Zimbabwe and use the services.
                    </ListItem>
                    <ListItem>
                        <strong>Service:</strong> refers to the service provided by
                        Butterflies of Zimbabwe as described in the relative terms (if
                        available) and on this platform.
                    </ListItem>
                    <ListItem>
                        <strong>Third-party service:</strong> refers to advertisers,
                        contest sponsors, promotional and marketing partners, and others
                        who provide our content or whose products or services we think may
                        interest you.
                    </ListItem>
                    <ListItem>
                        <strong>Website:</strong> Butterflies of Zimbabwe's site, which can
                        be accessed via this URL:
                    </ListItem>
                    <ListItem>
                        <strong>You:</strong> a person or entity that is registered with
                        Butterflies of Zimbabwe to use the Services.
                    </ListItem>
                </UnorderedList>

                <Heading as="h2" size="lg">
                    Restrictions
                </Heading>
                <Text>You agree not to, and you will not permit others to:</Text>
                <UnorderedList spacing={2}>
                    <ListItem>
                        License, sell, rent, lease, assign, distribute, transmit, host,
                        outsource, disclose or otherwise commercially exploit the app or
                        make the platform available to any third party.
                    </ListItem>
                    <ListItem>
                        Modify, make derivative works of, disassemble, decrypt, reverse
                        compile or reverse engineer any part of the app.
                    </ListItem>
                    <ListItem>
                        Remove, alter or obscure any proprietary notice (including any
                        notice of copyright or trademark) of Butterflies of Zimbabwe or its
                        affiliates, partners, suppliers or the licensors of the app.
                    </ListItem>
                </UnorderedList>

                <Heading as="h2" size="lg">
                    Return and Refund Policy
                </Heading>
                <Text>
                    Thanks for shopping at Butterflies of Zimbabwe. We appreciate the fact
                    that you like to buy the stuff we build. We also want to make sure you
                    have a rewarding experience while you’re exploring, evaluating, and
                    purchasing our products.
                </Text>
                <Text>
                    As with any shopping experience, there are terms and conditions that
                    apply to transactions at Butterflies of Zimbabwe. We’ll be as brief as
                    our attorneys will allow. The main thing to remember is that by
                    placing an order or making a purchase at Butterflies of Zimbabwe, you
                    agree to the terms along with Butterflies of Zimbabwe's Privacy
                    Policy.
                </Text>
                <Text>
                    If, for any reason, You are not completely satisfied with any good or
                    service that we provide, don't hesitate to contact us and we will
                    discuss any of the issues you are going through with our product.
                </Text>

                <Heading as="h2" size="lg">
                    Your Suggestions
                </Heading>
                <Text>
                    Any feedback, comments, ideas, improvements or suggestions
                    (collectively, "Suggestions") provided by you to Butterflies of
                    Zimbabwe with respect to the app shall remain the sole and exclusive
                    property of Butterflies of Zimbabwe.
                </Text>
                <Text>
                    Butterflies of Zimbabwe shall be free to use, copy, modify, publish,
                    or redistribute the Suggestions for any purpose and in any way
                    without any credit or any compensation to you.
                </Text>

                <Heading as="h2" size="lg">
                    Your Consent
                </Heading>
                <Text>
                    We've updated our Terms &amp; Conditions to provide you with complete
                    transparency into what is being set when you visit our site and how
                    it's being used. By using our app, registering an account, or making a
                    purchase, you hereby consent to our Terms &amp; Conditions.
                </Text>

                <Heading as="h2" size="lg">
                    Links to Other Websites
                </Heading>
                <Text>
                    This Terms &amp; Conditions applies only to the Services. The Services
                    may contain links to other websites not operated or controlled by
                    Butterflies of Zimbabwe. We are not responsible for the content,
                    accuracy or opinions expressed in such websites, and such websites are
                    not investigated, monitored or checked for accuracy or completeness by
                    us. Please remember that when you use a link to go from the Services
                    to another website, our Terms &amp; Conditions are no longer in
                    effect. Your browsing and interaction on any other website, including
                    those that have a link on our platform, is subject to that website’s
                    own rules and policies. Such third parties may use their own cookies
                    or other methods to collect information about you.
                </Text>

                <Heading as="h2" size="lg">
                    Cookies
                </Heading>
                <Text>
                    Butterflies of Zimbabwe uses "Cookies" to identify the areas of our
                    website that you have visited. A Cookie is a small piece of data
                    stored on your computer or mobile device by your web browser. We use
                    Cookies to enhance the performance and functionality of our app but
                    are non-essential to their use. However, without these cookies,
                    certain functionality like videos may become unavailable or you would
                    be required to enter your login details every time you visit the app
                    as we would not be able to remember that you had logged in previously.
                    Most web browsers can be set to disable the use of Cookies. However,
                    if you disable Cookies, you may not be able to access functionality on
                    our website correctly or at all. We never place Personally Identifiable
                    Information in Cookies.
                </Text>

                <Heading as="h2" size="lg">
                    Changes To Our Terms &amp; Conditions
                </Heading>
                <Text>
                    You acknowledge and agree that Butterflies of Zimbabwe may stop
                    (permanently or temporarily) providing the Service (or any features
                    within the Service) to you or to users generally at sole discretion,
                    without prior notice to you. You may stop using the Service at any
                    time. You do not need to specifically inform Butterflies of Zimbabwe
                    when you stop using the Service. You acknowledge and agree that if
                    Butterflies of Zimbabwe disables access to your account, you may be
                    prevented from accessing the Service, your account details or any
                    files or other materials which is contained in your account.
                </Text>
                <Text>
                    If we decide to change our Terms &amp; Conditions, we will post those
                    changes on this page, and/or update the Terms &amp; Conditions
                    modification date below.
                </Text>

                <Heading as="h2" size="lg">
                    Modifications to Our app
                </Heading>
                <Text>
                    Butterflies of Zimbabwe reserves the right to modify, suspend or
                    discontinue, temporarily or permanently, the app or any service to
                    which it connects, with or without notice and without liability to
                    you.
                </Text>

                <Heading as="h2" size="lg">
                    Updates to Our app
                </Heading>
                <Text>
                    Butterflies of Zimbabwe may from time to time provide enhancements or
                    improvements to the features/ functionality of the app, which may
                    include patches, bug fixes, updates, upgrades and other modifications
                    ("Updates").
                </Text>
                <Text>
                    Updates may modify or delete certain features and/or functionalities
                    of the app. You agree that Butterflies of Zimbabwe has no obligation
                    to (i) provide any Updates, or (ii) continue to provide or enable any
                    particular features and/or functionalities of the app to you.
                </Text>
                <Text>
                    You further agree that all Updates will be (i) deemed to constitute an
                    integral part of the app, and (ii) subject to the terms and conditions
                    of this Agreement.
                </Text>

                <Heading as="h2" size="lg">
                    Third-Party Services
                </Heading>
                <Text>
                    We may display, include or make available third-party content
                    (including data, information, applications and other products
                    services) or provide links to third-party websites or services
                    ("Third- Party Services").
                </Text>
                <Text>
                    You acknowledge and agree that Butterflies of Zimbabwe shall not be
                    responsible for any Third-Party Services, including their accuracy,
                    completeness, timeliness, validity, copyright compliance, legality,
                    decency, quality or any other aspect thereof. Butterflies of Zimbabwe
                    does not assume and shall not have any liability or responsibility to
                    you or any other person or entity for any Third-Party Services.
                </Text>
                <Text>
                    Third-Party Services and links thereto are provided solely as a
                    convenience to you and you access and use them entirely at your own
                    risk and subject to such third parties' terms and conditions.
                </Text>

                <Heading as="h2" size="lg">
                    Term and Termination
                </Heading>
                <Text>
                    This Agreement shall remain in effect until terminated by you or
                    Butterflies of Zimbabwe.
                </Text>
                <Text>
                    Butterflies of Zimbabwe may, in its sole discretion, at any time and
                    for any or no reason, suspend or terminate this Agreement with or
                    without prior notice.
                </Text>
                <Text>
                    This Agreement will terminate immediately, without prior notice from
                    Butterflies of Zimbabwe, in the event that you fail to comply with any
                    provision of this Agreement. You may also terminate this Agreement by
                    deleting the app and all copies thereof from your computer.
                </Text>
                <Text>
                    Upon termination of this Agreement, you shall cease all use of the app
                    and delete all copies of the app from your computer.
                </Text>
                <Text>
                    Termination of this Agreement will not limit any of Butterflies of
                    Zimbabwe's rights or remedies at law or in equity in case of breach by
                    you (during the term of this Agreement) of any of your obligations
                    under the present Agreement.
                </Text>

                <Heading as="h2" size="lg">
                    Copyright Infringement Notice
                </Heading>
                <Text>
                    If you are a copyright owner or such owner’s agent and believe any
                    material on our app constitutes an infringement on your copyright,
                    please contact us setting forth the following information: (a) a
                    physical or electronic signature of the copyright owner or a person
                    authorized to act on his behalf; (b) identification of the material
                    that is claimed to be infringing; (c) your contact information,
                    including your address, telephone number, and an email; (d) a
                    statement by you that you have a good faith belief that use of the
                    material is not authorized by the copyright owners; and (e) a
                    statement that the information in the notification is accurate, and,
                    under penalty of perjury you are authorized to act on behalf of the
                    owner.
                </Text>

                <Heading as="h2" size="lg">
                    Indemnification
                </Heading>
                <Text>
                    You agree to indemnify and hold Butterflies of Zimbabwe and its
                    parents, subsidiaries, affiliates, officers, employees, agents,
                    partners and licensors (if any) harmless from any claim or demand,
                    including reasonable attorneys' fees, due to or arising out of your:
                    (a) use of the app; (b) violation of this Agreement or any law or
                    regulation; or (c) violation of any right of a third party.
                </Text>

                <Heading as="h2" size="lg">
                    No Warranties
                </Heading>
                <Text>
                    The app is provided to you "AS IS" and "AS AVAILABLE" and with all
                    faults and defects without warranty of any kind. To the maximum extent
                    permitted under applicable law, Butterflies of Zimbabwe, on its own
                    behalf and on behalf of its affiliates and its and their respective
                    licensors and service providers, expressly disclaims all warranties,
                    whether express, implied, statutory or otherwise, with respect to the
                    app...
                </Text>
                <Text>
                    Without limiting the foregoing, neither Butterflies of Zimbabwe nor
                    any Butterflies of Zimbabwe's provider makes any representation or
                    warranty of any kind, express or implied...
                </Text>

                <Heading as="h2" size="lg">
                    Limitation of Liability
                </Heading>
                <Text>
                    Notwithstanding any damages that you might incur, the entire liability
                    of Butterflies of Zimbabwe and any of its suppliers under any
                    provision of this Agreement and your exclusive remedy for all of the
                    foregoing shall be limited to the amount actually paid by you for the
                    app.
                </Text>
                <Text>
                    To the maximum extent permitted by applicable law, in no event shall
                    Butterflies of Zimbabwe or its suppliers be liable for any special,
                    incidental, indirect, or consequential damages whatsoever...
                </Text>

                <Heading as="h2" size="lg">
                    Severability
                </Heading>
                <Text>
                    If any provision of this Agreement is held to be unenforceable or
                    invalid, such provision will be changed and interpreted to accomplish
                    the objectives of such provision to the greatest extent possible
                    under applicable law and the remaining provisions will continue in
                    full force and effect.
                </Text>

                <Heading as="h2" size="lg">
                    Waiver
                </Heading>
                <Text>
                    Except as provided herein, the failure to exercise a right or to
                    require performance of an obligation under this Agreement shall not
                    effect a party's ability to exercise such right or require such
                    performance at any time thereafter nor shall the waiver of a breach
                    constitute waiver of any subsequent breach.
                </Text>
                <Text>
                    No failure to exercise, and no delay in exercising, on the part of
                    either party, any right or any power under this Agreement shall
                    operate as a waiver of that right or power...
                </Text>

                <Heading as="h2" size="lg">
                    Amendments to this Agreement
                </Heading>
                <Text>
                    Butterflies of Zimbabwe reserves the right, at its sole discretion, to
                    modify or replace this Agreement at any time. If a revision is
                    material we will provide at least 30 days' notice prior to any new
                    terms taking effect. What constitutes a material change will be
                    determined at our sole discretion.
                </Text>
                <Text>
                    By continuing to access or use our app after any revisions become
                    effective, you agree to be bound by the revised terms...
                </Text>

                <Heading as="h2" size="lg">
                    Entire Agreement
                </Heading>
                <Text>
                    The Agreement constitutes the entire agreement between you and
                    Butterflies of Zimbabwe regarding your use of the app and supersedes
                    all prior and contemporaneous written or oral agreements between you
                    and Butterflies of Zimbabwe.
                </Text>
                <Text>
                    You may be subject to additional terms and conditions that apply when
                    you use or purchase other Butterflies of Zimbabwe's services, which
                    Butterflies of Zimbabwe will provide to you at the time of such use or
                    purchase.
                </Text>

                <Heading as="h2" size="lg">
                    Updates to Our Terms
                </Heading>
                <Text>
                    We may change our Service and policies, and we may need to make
                    changes to these Terms so that they accurately reflect our Service and
                    policies...
                </Text>

                <Heading as="h2" size="lg">
                    Intellectual Property
                </Heading>
                <Text>
                    The app and its entire contents, features and functionality (including
                    but not limited to all information, software, text, displays, images,
                    video and audio...
                </Text>

                <Heading as="h2" size="lg">
                    Agreement to Arbitrate
                </Heading>
                <Text>
                    This section applies to any dispute EXCEPT IT DOESN’T INCLUDE A
                    DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE OR EQUITABLE RELIEF...
                </Text>

                <Heading as="h2" size="lg">
                    Notice of Dispute
                </Heading>
                <Text>
                    In the event of a dispute, you or Butterflies of Zimbabwe must give
                    the other a Notice of Dispute...
                </Text>

                <Heading as="h2" size="lg">
                    Binding Arbitration
                </Heading>
                <Text>
                    If you and Butterflies of Zimbabwe don’t resolve any dispute by
                    informal negotiation, any other effort to resolve the dispute will be
                    conducted exclusively by binding arbitration...
                </Text>

                <Heading as="h2" size="lg">
                    Submissions and Privacy
                </Heading>
                <Text>
                    In the event that you submit or post any ideas, creative suggestions,
                    designs, photographs, information...
                </Text>

                <Heading as="h2" size="lg">
                    Promotions
                </Heading>
                <Text>
                    Butterflies of Zimbabwe may, from time to time, include contests,
                    promotions, sweepstakes, or other activities...
                </Text>

                <Heading as="h2" size="lg">
                    Typographical Errors
                </Heading>
                <Text>
                    In the event a product and/or service is listed at an incorrect price
                    or with incorrect information...
                </Text>

                <Heading as="h2" size="lg">
                    Miscellaneous
                </Heading>
                <Text>
                    If for any reason a court of competent jurisdiction finds any
                    provision or portion of these Terms &amp; Conditions to be
                    unenforceable, the remainder...
                </Text>

                <Heading as="h2" size="lg">
                    Disclaimer
                </Heading>
                <Text>
                    Butterflies of Zimbabwe is not responsible for any content, code or
                    any other imprecision...
                </Text>
                <Text>Butterflies of Zimbabwe does not provide warranties or guarantees...</Text>
                <Text>
                    In no event shall Butterflies of Zimbabwe be liable for any special,
                    direct, indirect, consequential, or incidental damages...
                </Text>

                <Heading as="h2" size="lg">
                    Contact Us
                </Heading>
                <Text>Don't hesitate to contact us if you have any questions.</Text>
                <UnorderedList>
                    <ListItem>Via Email: [email protected]</ListItem>
                </UnorderedList>
            </VStack>
        </Container>
    );
}

export default Terms;
